# Nodered Image for the IQRF IoT Starter Kit run on UP board

FROM nodered/node-red-docker:latest 
MAINTAINER Vojtěch Novák "jotio@outlook.com"

# install ext.
RUN	npm i node-red/node-red-dashboard \
	&& npm i node-red-node-watson \
	&& npm i node-red-contrib-scx-ibmiotapp \
